export const caspArr = [
    {
        id: 1,
        name: 'Barney Stinson',
        status: 'Alive',
        profession: 'Gamer',
        twitter: '@stinson',
        picture: 'barney.gif',
        alternativeText: 'Barney pointing at you',
        selected: true,
        initial: 'B',
    },
    {
        name: 'The Farytales',
        status: 'RIP',
        profession: 'Influencer',
        twitter: 'pending',
        picture: 'fary.jpg',
        alternativeText: 'The Fary pointing at you',
        id: 2,
        selected: false,
        initial: 'F',
    },
    {
        id: 3,
        name: ' Asch Ketchup',
        status: 'Alive',
        profession: 'Java developer',
        twitter: '@fryKetchup',
        picture: 'asch.png',
        alternativeText: 'Asch pointing at you',
        selected: true,
        initial: 'J',
    },
];
